CREATE TABLE IF NOT EXISTS pylon_pdf_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_type VARCHAR(64) NOT NULL DEFAULT 'proposal',
  source_id VARCHAR(128) NULL,
  proposal_id VARCHAR(128) NULL,
  proposal_number VARCHAR(128) NULL,
  customer_id VARCHAR(128) NULL,
  customer_name VARCHAR(255) NULL,
  pylon_url TEXT NOT NULL,
  status ENUM('pending', 'claimed', 'completed', 'failed', 'manual_login_required', 'cancelled') NOT NULL DEFAULT 'pending',
  priority INT NOT NULL DEFAULT 0,
  attempts INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 3,
  claimed_by VARCHAR(128) NULL,
  claimed_at DATETIME NULL,
  available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  last_error TEXT NULL,
  notes TEXT NULL,
  metadata_json JSON NULL,
  created_by VARCHAR(128) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pylon_pdf_jobs_status_available (status, available_at, priority, id),
  KEY idx_pylon_pdf_jobs_claimed_by (claimed_by, claimed_at),
  KEY idx_pylon_pdf_jobs_proposal (proposal_id),
  KEY idx_pylon_pdf_jobs_customer (customer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pylon_documents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_id BIGINT UNSIGNED NULL,
  proposal_id VARCHAR(128) NULL,
  proposal_number VARCHAR(128) NULL,
  customer_id VARCHAR(128) NULL,
  customer_name VARCHAR(255) NULL,
  document_type VARCHAR(64) NOT NULL DEFAULT 'proposal_pdf',
  pylon_document_id VARCHAR(128) NULL,
  file_name VARCHAR(255) NOT NULL,
  storage_path TEXT NOT NULL,
  sha256_hash CHAR(64) NULL,
  file_size_bytes BIGINT UNSIGNED NULL,
  mime_type VARCHAR(128) NOT NULL DEFAULT 'application/pdf',
  downloaded_by VARCHAR(128) NULL,
  downloaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_pylon_documents_pylon_document_id (pylon_document_id),
  KEY idx_pylon_documents_job (job_id),
  KEY idx_pylon_documents_proposal (proposal_id),
  KEY idx_pylon_documents_customer (customer_id),
  KEY idx_pylon_documents_downloaded_at (downloaded_at),
  CONSTRAINT fk_pylon_documents_job
    FOREIGN KEY (job_id) REFERENCES pylon_pdf_jobs(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
